project_id = "zupjsghppxyvmgwxvycc"

[functions.ai-assist]
verify_jwt = false

[functions.cleanup-deleted-notes]
verify_jwt = false

[functions.spell-check]
verify_jwt = false

[functions.notify-note-update]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-portal]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false
