// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://viidccjyjeipulbqqwua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpaWRjY2p5amVpcHVsYnFxd3VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjY4ODEsImV4cCI6MjA2ODM0Mjg4MX0._79sE__CrRgSOMuycMUt5_3tH2oyWC91TDiz4qleOJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    storageKey: 'supabase.auth.token',
    debug: false,
  },
  global: {
    headers: {
      'X-Client-Info': 'noteily-app',
    },
  },
});